lets test with a temp runner called zirconium

diff --git a/.gitlab/run-on-commits.gitlab-ci.yml b/.gitlab/run-on-commits.gitlab-ci.yml
--- a/.gitlab/run-on-commits.gitlab-ci.yml
+++ b/.gitlab/run-on-commits.gitlab-ci.yml
@@ -430,7 +430,7 @@ deploy:oxygen:
   variables:
     DEPLOY_SUDO_PASS: "EMSSRunner1"
   environment:
-    name: oxygen
+    name: uranium
     url: https://131.110.163.12
     action: access # See "action: access" comment on .carbon-access above
 
@@ -441,6 +441,14 @@ deploy:oxygen:
   environment:
     name: uranium
     url: https://131.110.163.12
+
+.zirconium-deploy:
+  tags: ["ec2"]
+  variables:
+    DEPLOY_SUDO_PASS: "EMSSRunner1"
+  environment:
+    name: uranium
+    url: https://131.110.163.29
 
 .emss-fitdock-deploy-aws:
   stage: stageless
@@ -517,6 +525,32 @@ deploy:oxygen:
     # versus just `git pull origin fitdock --ff-only`, because CentOS 7 does not
     # have `--ff-only` on the `pull` subcommand.
     - >
+      if ! yq --version; then
+        INITIAL_DIR=$(pwd)
+        cd /opt/fitdock
+        sudo git fetch origin
+        sudo git merge origin/fitdock --ff-only
+        sudo bash /opt/fitdock/src/scripts/setup-fitdock.sh
+        cd "${INITIAL_DIR}"
+      fi
+
+    # Get install_dir from .fitdock.yml using `yq` command (like jq but for yaml)
+    - export INSTALL_DIR=$(yq -r .install_dir ./.fitdock.yml)
+    - echo "Using install directory ${INSTALL_DIR}"
+
+    # Run `fitdock` if necessary
+    # --------------------------
+    #
+    # If changes have been made to .fitdock.yml, or if `[fitdock]` is
+    # in the commit message, run the fitdock command
+    - >
+      if [[ "${CI_COMMIT_TITLE}" =~ \[fitdock\] ]] || ! cmp --silent ./.fitdock.yml "${INSTALL_DIR}/.fitdock.yml"; then
+        echo "do deploy";
+        sudo mkdir -p "${INSTALL_DIR}"
+        sudo chown gitlab-runner:gitlab-runner "${INSTALL_DIR}"
+        /bin/cp -f ./.fitdock.yml "${INSTALL_DIR}/.fitdock.yml"
+        sudo fitdock "${INSTALL_DIR}/.fitdock.yml"
+      fi
 
     # Make an obvious error if Docker is missing
     - >
@@ -524,6 +558,9 @@ deploy:oxygen:
         >&2 echo "Docker is not installed on the host"
         exit 1
       fi
+
+    # Docker command could be in different locations
+    - DOCKER_BIN=$(command -v docker)
 
     - |
       cat <<EOF
@@ -574,6 +611,73 @@ deploy:oxygen:
     # Capture the final value
     - RSYSLOG_FINAL_CONFIG=$(cat /tmp/emss-rsyslog.conf)
 
+    # Function to disable rsyslog forwarding of logs. This is a function just
+    # for slightly easier readability.
+    - |
+      disableRsyslogForwarding() {
+        echo "{RSYSLOG_DISABLE_FORWARDING} = true, disabling forwarding EMSS logs"
+        if [[ -e "${RSYSLOG_EMSS_CONFIG_FILE}" ]]; then
+          echo "${RSYSLOG_EMSS_CONFIG_FILE} exists; removing and restarting Rsyslog. ${RSYSLOG_EMSS_CONFIG_FILE} was:"
+          cat "${RSYSLOG_EMSS_CONFIG_FILE}"
+          sudo rm -rf "${RSYSLOG_EMSS_CONFIG_FILE}"
+          sudo systemctl restart rsyslog
+          sleep 5
+          sudo systemctl status rsyslog
+        else
+          echo "${RSYSLOG_EMSS_CONFIG_FILE} does not exist; nothing to do."
+        fi
+      }
+
+    # Multi-OS approach to install rsyslog-gnutils
+    - |
+      install_rsyslog_gnutls() {
+        if command -v apt-get >/dev/null; then
+          sudo apt-get update
+          sudo apt-get install -y rsyslog-gnutls
+        elif command -v yum >/dev/null; then
+          sudo yum install -y rsyslog-gnutls
+        elif command -v dnf >/dev/null; then
+          sudo dnf install -y rsyslog-gnutls
+        else
+          echo "Unsupported package manager. Cannot install rsyslog-gnutls."
+          exit 1
+        fi
+      }
+
+    # Function to update EMSS-specific Rsyslog config file, and restart Rsyslog
+    # to pickup changes. This is a function just for slightly easier readability.
+    #   1. Print messages, including diff
+    #   2. Write the content to $RSYSLOG_EMSS_CONFIG_FILE file
+    #   3. Ensure rsyslog-gnutls installed (really only necessary on initial setup)
+    #   4. Restart rsyslog
+    #   5. Give it a few seconds to ensure started up
+    #   6. Print status of Rsyslog
+    - |
+      updateRsyslogConfig() {
+        echo "Rsyslog EMSS config file $RSYSLOG_EMSS_CONFIG_FILE changed. Changes were:"
+        diff -u <(echo "$RSYSLOG_INITIAL_CONFIG") <(echo "$RSYSLOG_FINAL_CONFIG") || true
+        sudo rm -rf ${RSYSLOG_EMSS_CONFIG_FILE}
+        sudo mv /tmp/emss-rsyslog.conf ${RSYSLOG_EMSS_CONFIG_FILE}
+        echo "Restarting Rsyslog."
+        install_rsyslog_gnutls
+        sudo systemctl restart rsyslog
+        sleep 5
+        sudo systemctl status rsyslog
+      }
+
+
+    # Use functions above to alter Rsyslog config as necessary
+    - |
+      if [ "${RSYSLOG_DISABLE_FORWARDING}" == "true" ]; then
+        disableRsyslogForwarding
+      else
+        if [ "${RSYSLOG_INITIAL_CONFIG}" != "${RSYSLOG_FINAL_CONFIG}" ]; then
+          updateRsyslogConfig
+        else
+          echo "Rsyslog EMSS config file $RSYSLOG_EMSS_CONFIG_FILE unchanged. No further Rsyslog actions."
+        fi
+      fi
+
     - |
       cat <<EOF
       # # # # # # # # # # # # # # # # # # # # # #
@@ -598,7 +702,7 @@ deploy:oxygen:
     - COMPOSE_FILES=$(sudo docker compose ls --all | tail -n +2 | awk '{ print $NF }')
 
     # Print to job log, just for info
-    - sudo docker compose ls --all
+    - sudo $DOCKER_BIN compose ls --all
 
     # Loop over everything in COMPOSE_FILES (whether running, exited, or otherwise), and
     # stop/remove any of them that aren't $INSTALL_DIR/docker-compose.yml
@@ -611,13 +715,13 @@ deploy:oxygen:
             echo "$file is the docker-compose file for this app. Keep it running."
           else
             echo "$file is the docker-compose file for another app. Stopping and removing it."
-            sudo docker compose --file "$file" rm --stop --volumes --force
+            sudo $DOCKER_BIN compose --file "$file" rm --stop --volumes --force
           fi
         done
       fi
 
     # Print to job log after possible changes above, just for info
-    - sudo docker compose ls --all
+    - sudo $DOCKER_BIN compose ls --all
 
     - |
       cat <<EOF
@@ -639,28 +743,28 @@ deploy:oxygen:
 
     # Take docker-compose down, pull latest, bring it back up
     - cd "${INSTALL_DIR}"
-    - echo $CI_JOB_TOKEN | sudo /usr/bin/docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
+    - echo $CI_JOB_TOKEN | sudo $DOCKER_BIN login -u gitlab-ci-token --password-stdin $CI_REGISTRY
 
     # Get the latest of each image
-    - sudo /usr/bin/docker compose pull
+    - sudo $DOCKER_BIN compose pull
 
     # Using the new images, re-up Compose. Also remove anything no longer defined in
     # docker-compose.yml via --remove-orphans
-    - sudo /usr/bin/docker compose up -d --remove-orphans
+    - sudo $DOCKER_BIN compose up -d --remove-orphans
 
     # remove any images, networks, or volumes no longer in use
-    - sudo /usr/bin/docker image prune --all --force
-    - sudo /usr/bin/docker network prune --force
-    - sudo /usr/bin/docker volume prune --all --force
+    - sudo $DOCKER_BIN image prune --all --force
+    - sudo $DOCKER_BIN network prune --force
+    - sudo $DOCKER_BIN volume prune --all --force
 
     # Print info on all docker networks
     - |
-      for id in $(sudo docker network ls -q); do
-        sudo docker network inspect "$id";
+      for id in $(sudo $DOCKER_BIN network ls -q); do
+        sudo $DOCKER_BIN network inspect "$id";
       done
 
     # print docker system info
-    - sudo /usr/bin/docker system df
+    - sudo $DOCKER_BIN system df
 
     # Report to logging server that a deploy has occurred.
     # The variables from .env below are available because of the
@@ -684,6 +788,7 @@ deploy:oxygen:
       \"jobUrl\":\"${CI_JOB_URL}\",
       \"pipelineUrl\":\"${CI_PIPELINE_URL}\"
       }}"
+
 
     # Print helpful reminders on how deploy can be modified by env vars
     - |
@@ -714,6 +819,19 @@ deploy:uranium:
   before_script:
     - sed -i "s/INSERT_SUBDOMAIN/uranium-emss-dev/g" .env
     - sed -i "s/INSERT_LOG_DATA_SERVER_NAME/uranium/g" .env
+
+deploy:zirconium:
+  extends:
+    - .emss-fitdock-deploy-aws
+    - .zirconium-deploy
+  needs:
+    - make-dotenv
+    - docker:retag
+    - deploy:artifactize-committed-files
+  when: manual
+  before_script:
+    - sed -i "s/INSERT_SUBDOMAIN/zirconium-emss-dev/g" .env
+    - sed -i "s/INSERT_LOG_DATA_SERVER_NAME/zirconium/g" .env
 
 deploy:int:
   extends: .deploy-template
